package io.openems.edge.simulator.temperature;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
        name = "Simulator Temperature Passing", //
        description = "This simulates a the Temperature Change if the Controller Passing and Overseer are active.")
@interface Config {

    @AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
    String id() default "TemperatureSimulator0";

    @AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
    String alias() default "";

    @AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
    boolean enabled() default true;

    @AttributeDefinition(name = "Datasource-ID", description = "ID of Simulator Datasource.")
    String datasource_id() default "temperature-standard-load-profile";

    @AttributeDefinition(name = "Datasource target filter", description = "This is auto-generated by 'Datasource-ID'.")
    String datasource_target() default "";

    @AttributeDefinition(name = "PF-Sensor", description = "Temperature Sensor used for PF in Passing Controller.")
            String pf_Sensor() default "TemperatureSensor0";

    @AttributeDefinition(name = "PR-Sensor", description = "Temperature Sensor used for PR in Passing Controller.")
    String pr_Sensor() default "TemperatureSensor1";

    @AttributeDefinition(name = "SF-Sensor", description = "Temperature Sensor used for SF in Passing Controller.")
    String sf_Sensor() default "TemperatureSensor2";

    @AttributeDefinition(name = "SR-Sensor", description = "Temperature Sensor used for SR in Passing Controller.")
    String sr_Sensor() default "TemperatureSensor3";

    @AttributeDefinition(name = "Overseer-Sensor", description = "Temperature Sensor used in Overseeing Controller.")
    String goal_Sensor() default "TemperatureSensor4";

    String webconsole_configurationFactory_nameHint() default "Simulator Tenoerature-Passing [{id}]";

}